version: '3.8'

services:
  app:
    build: .
    container_name: email-service
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - NODE_ENV=production
    ports:
      - "8800:8800" # Cambia este puerto si necesitas
    networks:
      - app-network
    command: ["node", "consumer.js"]

networks:
  app-network:
    external: true
